# Generated by Django 5.2.6 on 2025-09-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['grade', 'name'],
                'unique_together': {('grade', 'name')},
            },
        ),
    ]
