# Generated by Django 5.2.6 on 2026-09-14 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Example: 2026', max_length=20, unique=True)),
                ('is_current', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('term_1', 'Term 1'), ('term_2', 'Term 2'), ('term_3', 'Term 3')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='academics.academicyear')),
            ],
            options={
                'ordering': ['academic_year', 'term'],
            },
        ),
        migrations.CreateModel(
            name='AcademicCalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('mid_term_break', 'Mid-Term Break'), ('school_holiday', 'School Holiday'), ('public_holiday', 'Public Holiday'), ('examination', 'Examination Period'), ('staff_day', 'Staff Day'), ('opening_day', 'School Opening Day'), ('closing_day', 'School Closing Day'), ('other', 'Other')], max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('is_school_closed', models.BooleanField(default=True, help_text='Indicates whether normal school operations are closed during this event.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('term', models.ForeignKey(blank=True, help_text='Optional. Leave blank for events that apply to the academic year rather than a specific term.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='academics.academicterm')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='academics.academicyear')),
            ],
            options={
                'ordering': ['start_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ClassLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['display_order'], name='academics_c_display_e96c4f_idx'), models.Index(fields=['is_active'], name='academics_c_is_acti_c2b8d4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.SlugField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='academics.classlevel')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='academicterm',
            constraint=models.UniqueConstraint(fields=('academic_year', 'term'), name='unique_term_per_academic_year'),
        ),
        migrations.AddIndex(
            model_name='academiccalendarevent',
            index=models.Index(fields=['academic_year', 'start_date'], name='academics_a_academi_183123_idx'),
        ),
        migrations.AddIndex(
            model_name='academiccalendarevent',
            index=models.Index(fields=['event_type'], name='academics_a_event_t_5233e7_idx'),
        ),
        migrations.AddIndex(
            model_name='academiccalendarevent',
            index=models.Index(fields=['is_active'], name='academics_a_is_acti_0d8e8b_idx'),
        ),
        migrations.AddIndex(
            model_name='stream',
            index=models.Index(fields=['class_level'], name='academics_s_class_l_bdf19e_idx'),
        ),
        migrations.AddIndex(
            model_name='stream',
            index=models.Index(fields=['is_active'], name='academics_s_is_acti_75c1a0_idx'),
        ),
        migrations.AddConstraint(
            model_name='stream',
            constraint=models.UniqueConstraint(fields=('class_level', 'name'), name='unique_stream_per_class_level'),
        ),
        migrations.AddConstraint(
            model_name='stream',
            constraint=models.UniqueConstraint(fields=('class_level', 'code'), name='unique_stream_code_per_class_level'),
        ),
    ]
