# Generated by Django 5.2.6 on 2026-09-17 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classlevel',
            name='next_class_level',
            field=models.ForeignKey(blank=True, help_text='The class level students normally progress to after completing this class. Leave blank for the final class.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_class_levels', to='academics.classlevel'),
        ),
        migrations.AddIndex(
            model_name='classlevel',
            index=models.Index(fields=['next_class_level'], name='academics_c_next_cl_9a9a00_idx'),
        ),
    ]
