# Generated by Django 5.2.6 on 2025-09-29 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolcalendar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentTermYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('1', 'Term 1'), ('2', 'Term 2'), ('3', 'Term 3')], max_length=1)),
                ('year', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('term', 'year')},
            },
        ),
    ]
