# Generated by Django 5.2.6 on 2026-09-11 08:56

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('department', models.CharField(choices=[('transport', 'Transport'), ('classes', 'Classes'), ('library', 'Library'), ('office', 'Office'), ('boarding', 'Boarding'), ('sports', 'Sports'), ('security', 'Security'), ('school_maintenance', 'School Maintenance'), ('catering_dining', 'Catering / Dining'), ('ict', 'ICT'), ('administration', 'Administration'), ('medical', 'Medical'), ('laboratory_science', 'Laboratory / Science'), ('human_resource', 'Human Resource'), ('agriculture', 'Agriculture'), ('utilities', 'Utilities')], max_length=50)),
                ('unit', models.CharField(choices=[('pieces', 'Pieces'), ('kg', 'Kilograms'), ('liters', 'Liters'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='Inventory_i_name_92fc3d_idx'), models.Index(fields=['department'], name='Inventory_i_departm_2161d9_idx'), models.Index(fields=['is_active'], name='Inventory_i_is_acti_cbc813_idx')],
            },
        ),
        migrations.CreateModel(
            name='InventoryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='Inventory_i_name_d42113_idx'), models.Index(fields=['is_active'], name='Inventory_i_is_acti_e9f6a9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('long_description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_stores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('transaction_type', models.CharField(choices=[('addition', 'Addition'), ('removal', 'Removal'), ('transfer', 'Transfer'), ('adjustment', 'Adjustment')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=14)),
                ('source_previous_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('source_resulting_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('destination_previous_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('destination_resulting_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('adjusted_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('reason', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to=settings.AUTH_USER_MODEL)),
                ('destination_inventory_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destination_inventory_transactions', to='Inventory.inventorylocation')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='Inventory.inventoryitem')),
                ('source_inventory_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_inventory_transactions', to='Inventory.inventorylocation')),
                ('destination_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destination_inventory_transactions', to='Inventory.store')),
                ('source_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_inventory_transactions', to='Inventory.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_records', to='Inventory.inventorylocation')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_records', to='Inventory.inventoryitem')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_records', to='Inventory.store')),
            ],
            options={
                'ordering': ['item__name'],
            },
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['name'], name='Inventory_s_name_9fff74_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['is_active'], name='Inventory_s_is_acti_3915b7_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['transaction_type'], name='Inventory_i_transac_41df96_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['item'], name='Inventory_i_item_id_57d20a_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['created_by'], name='Inventory_i_created_d438d4_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['created_at'], name='Inventory_i_created_011211_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['source_store'], name='Inventory_i_source__158951_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['source_inventory_location'], name='Inventory_i_source__d397ec_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['destination_store'], name='Inventory_i_destina_4b5cc4_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['destination_inventory_location'], name='Inventory_i_destina_217d29_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorystock',
            index=models.Index(fields=['item'], name='Inventory_i_item_id_5dff49_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorystock',
            index=models.Index(fields=['store'], name='Inventory_i_store_i_e27f46_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorystock',
            index=models.Index(fields=['inventory_location'], name='Inventory_i_invento_9113e5_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorystock',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='inventory_stock_quantity_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='inventorystock',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('inventory_location__isnull', True), ('store__isnull', False)), models.Q(('inventory_location__isnull', False), ('store__isnull', True)), _connector='OR'), name='stock_exactly_one_location'),
        ),
        migrations.AddConstraint(
            model_name='inventorystock',
            constraint=models.UniqueConstraint(condition=models.Q(('inventory_location__isnull', True), ('store__isnull', False)), fields=('item', 'store'), name='unique_item_per_store'),
        ),
        migrations.AddConstraint(
            model_name='inventorystock',
            constraint=models.UniqueConstraint(condition=models.Q(('inventory_location__isnull', False), ('store__isnull', True)), fields=('item', 'inventory_location'), name='unique_item_per_inventory_location'),
        ),
    ]
