# Generated by Django 5.2.6 on 2026-09-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_manager',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
