# Generated by Django 5.2.6 on 2026-09-12

import django.db.models.deletion
from django.db import migrations, models


DEPARTMENTS = [
    ("Transport", "transport"),
    ("Classes", "classes"),
    ("Library", "library"),
    ("Office", "office"),
    ("Boarding", "boarding"),
    ("Sports", "sports"),
    ("Security", "security"),
    ("School Maintenance", "school-maintenance"),
    ("Catering/Dining", "catering-dining"),
    ("ICT", "ict"),
    ("Administration", "administration"),
    ("Medical", "medical"),
    ("Laboratory/Science", "laboratory-science"),
    ("Human Resource", "human-resource"),
    ("Agriculture", "agriculture"),
    ("Utilities", "utilities"),
]


def normalize_department(value):
    if not value:
        return None

    value = str(value).strip().lower()

    aliases = {
        "transport": "transport",

        "classes": "classes",
        "class": "classes",

        "library": "library",

        "office": "office",

        "boarding": "boarding",

        "sports": "sports",
        "sport": "sports",

        "security": "security",

        "school_maintenance": "school-maintenance",
        "school-maintenance": "school-maintenance",
        "maintenance": "school-maintenance",

        "catering": "catering-dining",
        "dining": "catering-dining",
        "catering/dining": "catering-dining",
        "catering_dining": "catering-dining",
        "catering-dining": "catering-dining",

        "ict": "ict",

        "administration": "administration",
        "admin": "administration",

        "medical": "medical",

        "laboratory": "laboratory-science",
        "laboratory/science": "laboratory-science",
        "laboratory_science": "laboratory-science",
        "laboratory-science": "laboratory-science",

        "human_resource": "human-resource",
        "human resources": "human-resource",
        "human resource": "human-resource",
        "human-resources": "human-resource",
        "human-resource": "human-resource",

        "agriculture": "agriculture",

        "utilities": "utilities",
    }

    return aliases.get(value, value)


def create_departments_and_migrate_inventory_items(
    apps,
    schema_editor,
):
    Department = apps.get_model(
        "Receipts",
        "Department",
    )

    InventoryItem = apps.get_model(
        "Inventory",
        "InventoryItem",
    )

    department_map = {}

    # ---------------------------------------------------------
    # 1. Create the central Department records
    # ---------------------------------------------------------
    for name, code in DEPARTMENTS:

        department, _ = Department.objects.get_or_create(
            code=code,
            defaults={
                "name": name,
                "is_active": True,
            },
        )

        department_map[code] = department

    # ---------------------------------------------------------
    # 2. Migrate existing InventoryItem department values
    # ---------------------------------------------------------
    for item in InventoryItem.objects.all():

        old_value = getattr(
            item,
            "department_old",
            None,
        )

        if not old_value:
            continue

        code = normalize_department(old_value)

        if not code:
            continue

        department = department_map.get(code)

        # -----------------------------------------------------
        # Handle an old department that wasn't predefined.
        # -----------------------------------------------------
        if department is None:

            clean_name = (
                str(old_value)
                .replace("_", " ")
                .replace("-", " ")
                .strip()
            )

            department, _ = Department.objects.get_or_create(
                code=code,
                defaults={
                    "name": clean_name.title(),
                    "is_active": True,
                },
            )

            department_map[code] = department

        # -----------------------------------------------------
        # IMPORTANT:
        # The historical InventoryItem.department is already
        # a ForeignKey at this point.
        #
        # Therefore use department_id rather than assigning
        # the integer directly to item.department.
        # -----------------------------------------------------
        item.department_id = department.pk

        item.save(
            update_fields=["department"],
        )


class Migration(migrations.Migration):

    dependencies = [
        (
            "Inventory",
            "0002_alter_store_store_manager",
        ),
        (
            "Receipts",
            "0007_department_alter_receiptitem_options_and_more",
        ),
    ]

    operations = [

        # -----------------------------------------------------
        # 1. Preserve the old text department field.
        # -----------------------------------------------------
        migrations.RenameField(
            model_name="inventoryitem",
            old_name="department",
            new_name="department_old",
        ),

        # -----------------------------------------------------
        # 2. Create the new Department FK temporarily nullable.
        # -----------------------------------------------------
        migrations.AddField(
            model_name="inventoryitem",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inventory_items",
                to="Receipts.department",
            ),
        ),

        # -----------------------------------------------------
        # 3. Add SubDepartment FK.
        # -----------------------------------------------------
        migrations.AddField(
            model_name="inventoryitem",
            name="subdepartment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inventory_items",
                to="Receipts.subdepartment",
            ),
        ),

        # -----------------------------------------------------
        # 4. Update unit choices.
        # -----------------------------------------------------
        migrations.AlterField(
            model_name="inventoryitem",
            name="unit",
            field=models.CharField(
                choices=[
                    ("pieces", "Pieces"),
                    ("units", "Units"),
                    ("pairs", "Pairs"),
                    ("sets", "Sets"),
                    ("boxes", "Boxes"),
                    ("packs", "Packs"),
                    ("dozens", "Dozens"),
                    ("rolls", "Rolls"),
                    ("bundles", "Bundles"),
                    ("cartons", "Cartons"),
                    ("bags", "Bags"),
                    ("sacks", "Sacks"),
                    ("bottles", "Bottles"),
                    ("cans", "Cans"),
                    ("tins", "Tins"),
                    ("containers", "Containers"),
                    ("kg", "Kilograms"),
                    ("g", "Grams"),
                    ("mg", "Milligrams"),
                    ("tonnes", "Tonnes"),
                    ("liters", "Liters"),
                    ("ml", "Milliliters"),
                    ("cl", "Centiliters"),
                    ("gallons", "Gallons"),
                    ("meters", "Meters"),
                    ("cm", "Centimeters"),
                    ("mm", "Millimeters"),
                    ("km", "Kilometers"),
                    ("inches", "Inches"),
                    ("feet", "Feet"),
                    ("yards", "Yards"),
                    ("square_meters", "Square Meters"),
                    ("square_feet", "Square Feet"),
                    ("reams", "Reams"),
                    ("sheets", "Sheets"),
                    ("ream", "Ream"),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),

        # -----------------------------------------------------
        # 5. Create departments and migrate old values.
        # -----------------------------------------------------
        migrations.RunPython(
            create_departments_and_migrate_inventory_items,
            migrations.RunPython.noop,
        ),

        # -----------------------------------------------------
        # 6. Department is now required.
        # -----------------------------------------------------
        migrations.AlterField(
            model_name="inventoryitem",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inventory_items",
                to="Receipts.department",
            ),
        ),

        # -----------------------------------------------------
        # 7. Remove the old text department field.
        # -----------------------------------------------------
        migrations.RemoveField(
            model_name="inventoryitem",
            name="department_old",
        ),

        # -----------------------------------------------------
        # 8. Add subdepartment index.
        # -----------------------------------------------------
        migrations.AddIndex(
            model_name="inventoryitem",
            index=models.Index(
                fields=["subdepartment"],
                name="Inventory_i_subdepa_2e6c61_idx",
            ),
        ),
    ]

