# Generated by Django 5.2.6 on 2026-09-14 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_rename_inventory_i_departm_2161d9_idx_inventory_i_departm_03deac_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='inventoryitem',
            new_name='Inventory_i_departm_03deac_idx',
            old_name='Inventory_i_departm_2161d9_idx',
        ),
    ]
