# Generated by Django 5.2.6 on 2025-09-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('term', models.CharField(max_length=50)),
                ('due_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('1', 'Term 1'), ('2', 'Term 2'), ('3', 'Term 3')], max_length=10)),
                ('interview_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('registration_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tuition_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pocket_money', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('meals_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('boarding_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('swimming_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('textbook_fund_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('educational_trips_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('insurance_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('activity_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('rubric_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('others', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('transport_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('referral_discount_applied', models.BooleanField(default=False)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('year', models.PositiveIntegerField(default=2025)),
                ('payment_type', models.CharField(choices=[('M-Pesa', 'M-Pesa'), ('Bank Transfer', 'Bank Transfer'), ('Cash', 'Cash'), ('Agent', 'Agent')], max_length=50)),
                ('mpesa_ref_number', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_receipt_number', models.CharField(blank=True, max_length=100, null=True)),
                ('agent_reference_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GradeFeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('Playgroup', 'Playgroup'), ('PP1', 'PP1'), ('PP2', 'PP2'), ('Grade 1', 'Grade 1'), ('Grade 2', 'Grade 2'), ('Grade 3', 'Grade 3'), ('Grade 4', 'Grade 4'), ('Grade 5', 'Grade 5'), ('Grade 6', 'Grade 6'), ('Grade 7', 'Grade 7'), ('Grade 8', 'Grade 8'), ('Grade 9', 'Grade 9'), ('Grade 10', 'Grade 10'), ('Grade 11', 'Grade 11'), ('Grade 12', 'Grade 12')], max_length=20)),
                ('term', models.CharField(choices=[('1', 'Term 1'), ('2', 'Term 2'), ('3', 'Term 3')], max_length=10)),
                ('interview_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('registration_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tuition_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pocket_money', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('meals_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('boarding_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('swimming_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('textbook_fund_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('educational_trips_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('insurance_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('activity_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('rubric_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('others', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('year', models.PositiveIntegerField(default=2025)),
                ('total_fees', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='TransportFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100)),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
