# Generated by Django 5.2.6 on 2026-09-15 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='student',
        ),
        migrations.RemoveField(
            model_name='feepayment',
            name='student',
        ),
        migrations.DeleteModel(
            name='GradeFeeStructure',
        ),
        migrations.RemoveField(
            model_name='transportstage',
            name='route',
        ),
        migrations.DeleteModel(
            name='Fee',
        ),
        migrations.DeleteModel(
            name='FeePayment',
        ),
        migrations.DeleteModel(
            name='TransportRoute',
        ),
        migrations.DeleteModel(
            name='TransportStage',
        ),
    ]
