# Generated by Django 5.2.6 on 2026-09-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0004_delete_transportfee_transportstage_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepayment',
            name='year',
            field=models.PositiveIntegerField(default=2026),
        ),
        migrations.AlterField(
            model_name='gradefeestructure',
            name='year',
            field=models.PositiveIntegerField(default=2026),
        ),
    ]
