# Generated by Django 5.2.6 on 2026-09-15 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_id', models.CharField(editable=False, help_text='Unique family identifier, e.g. FAM-00001.', max_length=20, unique=True)),
                ('family_name', models.CharField(help_text='Family/household name, e.g. Mbaka Family.', max_length=150)),
                ('address', models.TextField(blank=True, help_text='Current physical/home address.')),
                ('town', models.CharField(blank=True, help_text='Town or locality where the family currently resides.', max_length=100)),
                ('county', models.CharField(blank=True, help_text='County where the family currently resides.', max_length=100)),
                ('sub_county', models.CharField(blank=True, help_text='Sub-county where the family currently resides.', max_length=100)),
                ('postal_address', models.CharField(blank=True, help_text='Postal address, if applicable.', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Family',
                'verbose_name_plural': 'Families',
                'ordering': ['family_name'],
            },
        ),
        migrations.CreateModel(
            name='ParentGuardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.CharField(editable=False, help_text='Unique parent/guardian identifier, e.g. PAR-00001.', max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('national_id_number', models.CharField(blank=True, help_text='National identification number.', max_length=50)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('not_specified', 'Not Specified')], default='not_specified', max_length=20)),
                ('mobile_number', models.CharField(max_length=30)),
                ('alternative_mobile', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('occupation', models.CharField(blank=True, max_length=150)),
                ('employer', models.CharField(blank=True, max_length=150)),
                ('address', models.TextField(blank=True, help_text='Use when the parent/guardian has a different residence from the family.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(blank=True, help_text='Family/household this parent or guardian belongs to.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parents_guardians', to='students.family')),
            ],
            options={
                'verbose_name': 'Parent / Guardian',
                'verbose_name_plural': 'Parents / Guardians',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(editable=False, help_text='Unique student identifier, e.g. STU-00001.', max_length=20, unique=True)),
                ('admission_number', models.CharField(help_text='Permanent school admission number.', max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(blank=True, max_length=150)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('not_specified', 'Not Specified')], default='not_specified', max_length=20)),
                ('nationality', models.CharField(blank=True, default='Kenyan', max_length=100)),
                ('birth_certificate_entry_number', models.CharField(blank=True, max_length=100)),
                ('birth_certificate_number', models.CharField(blank=True, max_length=100)),
                ('home_county', models.CharField(blank=True, help_text="Student's home/origin county.", max_length=100)),
                ('home_sub_county', models.CharField(blank=True, help_text="Student's home/origin sub-county.", max_length=100)),
                ('nemis_kemis_number', models.CharField(blank=True, help_text='NEMIS/KEMIS number, where available.', max_length=100)),
                ('child_assessment_number', models.CharField(blank=True, help_text='Child Assessment Number, where available.', max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/photos/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('graduated', 'Graduated'), ('transferred', 'Transferred'), ('withdrawn', 'Withdrawn'), ('inactive', 'Inactive')], default='active', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(blank=True, help_text='Family/household the student belongs to.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='students.family')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('birth_certificate', 'Birth Certificate'), ('previous_school_report', 'Previous School Report'), ('transfer_certificate', 'Transfer Certificate'), ('medical_form', 'Medical Form'), ('admission_form', 'Admission Form'), ('parent_guardian_document', 'Parent/Guardian Document'), ('other', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='students/documents/')),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.student')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_student_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Document',
                'verbose_name_plural': 'Student Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('relationship', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=30)),
                ('alternative_mobile', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('priority', models.PositiveIntegerField(default=1, help_text='Priority of this emergency contact. 1 represents the first contact.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='students.student')),
            ],
            options={
                'verbose_name': 'Emergency Contact',
                'verbose_name_plural': 'Emergency Contacts',
                'ordering': ['student', 'priority'],
                'constraints': [models.UniqueConstraint(fields=('student', 'priority'), name='unique_student_emergency_contact_priority')],
            },
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('transferred', 'Transferred'), ('withdrawn', 'Withdrawn'), ('inactive', 'Inactive')], default='active', max_length=30)),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('exit_reason', models.TextField(blank=True)),
                ('previous_school', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_enrollments', to='academics.academicyear')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_enrollments', to='academics.classlevel')),
                ('stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_enrollments', to='academics.stream')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Enrollment',
                'verbose_name_plural': 'Student Enrollments',
                'ordering': ['-academic_year__name', 'student__last_name'],
                'constraints': [models.UniqueConstraint(fields=('student', 'academic_year'), name='unique_student_academic_year_enrollment')],
            },
        ),
        migrations.CreateModel(
            name='StudentParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('mother', 'Mother'), ('father', 'Father'), ('step_mother', 'Step Mother'), ('step_father', 'Step Father'), ('guardian', 'Guardian'), ('grandparent', 'Grandparent'), ('aunt', 'Aunt'), ('uncle', 'Uncle'), ('sibling', 'Sibling'), ('other', 'Other')], max_length=30)),
                ('is_primary', models.BooleanField(default=False, help_text="Whether this is the student's primary parent/guardian.")),
                ('has_parental_responsibility', models.BooleanField(default=True)),
                ('receives_communications', models.BooleanField(default=True)),
                ('receives_fee_notifications', models.BooleanField(default=True)),
                ('is_emergency_contact', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_relationships', to='students.parentguardian')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_relationships', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Parent Relationship',
                'verbose_name_plural': 'Student Parent Relationships',
                'ordering': ['student', '-is_primary', 'parent_guardian__last_name'],
                'constraints': [models.UniqueConstraint(fields=('student', 'parent_guardian'), name='unique_student_parent_relationship')],
            },
        ),
    ]
