# Generated by Django 5.2.6 on 2026-09-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='birth_certificate_submitted',
            field=models.BooleanField(default=False, help_text="Whether the student's birth certificate has been submitted to the school."),
        ),
        migrations.AddField(
            model_name='student',
            name='has_allergies_or_illness',
            field=models.BooleanField(default=False, help_text='Whether the student has any known allergies or illnesses.'),
        ),
        migrations.AddField(
            model_name='student',
            name='has_special_abilities',
            field=models.BooleanField(default=False, help_text='Whether the student has any special abilities or talents that the school should know about.'),
        ),
        migrations.AddField(
            model_name='student',
            name='medical_conditions',
            field=models.TextField(blank=True, help_text='Details of known allergies, illnesses, or special medical conditions.'),
        ),
        migrations.AddField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, help_text="Student's religion or faith, if provided.", max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='special_abilities',
            field=models.TextField(blank=True, help_text="Description of the student's special abilities or talents."),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_certificate_entry_number',
            field=models.CharField(blank=True, help_text='Birth certificate entry number.', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_certificate_number',
            field=models.CharField(blank=True, help_text='Birth certificate number.', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='document_type',
            field=models.CharField(choices=[('birth_certificate', 'Birth Certificate'), ('previous_school_report', 'Previous School Report'), ('transfer_certificate', 'Transfer Certificate'), ('medical_form', 'Medical Form'), ('medical_document', 'Medical Document'), ('admission_form', 'Admission Form'), ('parent_guardian_document', 'Parent/Guardian Document'), ('other', 'Other')], max_length=50),
        ),
    ]
