# Generated by Django 5.2.6 on 2026-09-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_number',
            field=models.CharField(help_text='Permanent school admission number. Enter the existing admission number. The system will normalize it according to the configured admission-number format.', max_length=30, unique=True),
        ),
    ]
