# Generated by Django 5.2.6 on 2026-09-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_stream_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year_registered',
            field=models.PositiveIntegerField(default=2026),
        ),
    ]
