# Generated by Django 6.1 on 2026-08-18 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('department', models.CharField(choices=[('transport', 'Transport'), ('classes', 'Classes'), ('library', 'Library'), ('office', 'Office'), ('boarding', 'Boarding'), ('sports', 'Sports'), ('security', 'Security'), ('school_maintenance', 'School Maintenance'), ('catering_dining', 'Catering / Dining'), ('ict', 'ICT'), ('administration', 'Administration'), ('medical', 'Medical'), ('laboratory_science', 'Laboratory / Science'), ('human_resource', 'Human Resource'), ('agriculture', 'Agriculture'), ('utilities', 'Utilities')], max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('liters', 'Liters'), ('kg', 'Kg'), ('pieces', 'Pieces'), ('other', 'Other')], max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Receipts.receipt')),
            ],
            options={
                'verbose_name': 'Receipt Item',
                'verbose_name_plural': 'Receipt Items',
                'ordering': ['id'],
            },
        ),
    ]
