# Generated by Django 6.1 on 2026-08-18 13:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipts', '0002_receiptitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptitem',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='receiptitem',
            name='discount_applied',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AddField(
            model_name='receiptitem',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='receiptitem',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
