# Generated by Django 6.1 on 2026-08-21 05:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipts', '0003_receiptitem_discount_receiptitem_discount_applied_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiptitem',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='receiptitem',
            name='discount_applied',
        ),
        migrations.RemoveField(
            model_name='receiptitem',
            name='subtotal',
        ),
        migrations.AddField(
            model_name='receipt',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14),
        ),
        migrations.AlterField(
            model_name='receiptitem',
            name='total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=14),
        ),
    ]
