# Generated by Django 6.1 on 2026-08-22 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipts', '0004_remove_receiptitem_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
