# Generated by Django 5.2.6 on 2026-09-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipts', '0005_alter_receipt_payment_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('card', 'Card'), ('eft', 'EFT'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='receiptitem',
            name='unit',
            field=models.CharField(choices=[('pieces', 'Pieces'), ('kg', 'Kilograms'), ('liters', 'Liters'), ('other', 'Other')], max_length=20),
        ),
    ]
