# Generated by Django 5.2.6
# Customised to safely migrate existing ReceiptItem department values
# from the old text field to the new Department ForeignKey.

import django.db.models.deletion
from django.db import migrations, models


# ============================================================
# OLD DEPARTMENT VALUE → NEW DEPARTMENT
# ============================================================

DEPARTMENTS = [
    ("Transport", "transport"),
    ("Classes", "classes"),
    ("Library", "library"),
    ("Office", "office"),
    ("Boarding", "boarding"),
    ("Sports", "sports"),
    ("Security", "security"),
    ("School Maintenance", "school-maintenance"),
    ("Catering/Dining", "catering-dining"),
    ("ICT", "ict"),
    ("Administration", "administration"),
    ("Medical", "medical"),
    ("Laboratory/Science", "laboratory-science"),
    ("Human Resource", "human-resource"),
    ("Agriculture", "agriculture"),
    ("Utilities", "utilities"),
]


def create_departments_and_migrate_receipt_items(apps, schema_editor):
    """
    Create Department records and convert existing ReceiptItem
    department text values into Department foreign keys.
    """

    Department = apps.get_model("Receipts", "Department")
    ReceiptItem = apps.get_model("Receipts", "ReceiptItem")

    # --------------------------------------------------------
    # Create all Department records
    # --------------------------------------------------------

    department_map = {}

    for name, code in DEPARTMENTS:
        department = Department.objects.create(
            name=name,
            code=code,
            is_active=True,
        )

        department_map[code] = department

    # --------------------------------------------------------
    # Convert existing ReceiptItem department values
    # --------------------------------------------------------
    #
    # IMPORTANT:
    #
    # At this point the database column still contains
    # the OLD text values.
    #
    # Example:
    #
    # "human_resource"
    #
    # We convert that to the corresponding Department ID.
    # --------------------------------------------------------

    for item in ReceiptItem.objects.all():

        old_department = item.department

        if not old_department:
            continue

        # Normalize the old value
        old_department = str(old_department).strip().lower()

        # ----------------------------------------------------
        # Map old values to department codes
        # ----------------------------------------------------

        aliases = {
            "transport": "transport",
            "classes": "classes",
            "class": "classes",

            "library": "library",

            "office": "office",

            "boarding": "boarding",

            "sports": "sports",
            "sport": "sports",

            "security": "security",

            "school_maintenance": "school-maintenance",
            "school-maintenance": "school-maintenance",
            "maintenance": "school-maintenance",

            "catering": "catering-dining",
            "dining": "catering-dining",
            "catering/dining": "catering-dining",
            "catering_dining": "catering-dining",
            "catering-dining": "catering-dining",

            "ict": "ict",

            "administration": "administration",
            "admin": "administration",

            "medical": "medical",

            "laboratory": "laboratory-science",
            "laboratory/science": "laboratory-science",
            "laboratory_science": "laboratory-science",
            "laboratory-science": "laboratory-science",

            "human_resource": "human-resource",
            "human resources": "human-resource",
            "human resource": "human-resource",
            "human-resources": "human-resource",
            "human-resource": "human-resource",

            "agriculture": "agriculture",

            "utilities": "utilities",
        }

        department_code = aliases.get(old_department)

        if not department_code:
            raise ValueError(
                f"Unknown old department value "
                f"'{old_department}' for ReceiptItem "
                f"ID {item.pk}. "
                f"Add it to the aliases dictionary in "
                f"migration 0007."
            )

        department = department_map.get(department_code)

        if not department:
            raise ValueError(
                f"No Department was created for code "
                f"'{department_code}'."
            )

        # ----------------------------------------------------
        # Assign the FK
        # ----------------------------------------------------

        item.department = department.pk
        item.save(update_fields=["department"])


class Migration(migrations.Migration):

    dependencies = [
        (
            "Receipts",
            "0006_alter_receipt_payment_method_alter_receiptitem_unit",
        ),
    ]

    operations = [

        # ====================================================
        # 1. Create Department table
        # ====================================================

        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "code",
                    models.SlugField(
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),

        # ====================================================
        # 2. Create SubDepartment table
        #
        # This can safely be created before the FK conversion.
        # ====================================================

        migrations.CreateModel(
            name="SubDepartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                    ),
                ),
                (
                    "code",
                    models.SlugField(
                        max_length=100,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subdepartments",
                        to="Receipts.department",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),

        # ====================================================
        # 3. Change ReceiptItem.unit
        # ====================================================

        migrations.AlterField(
            model_name="receiptitem",
            name="unit",
            field=models.CharField(
                choices=[
                    ("pieces", "Pieces"),
                    ("units", "Units"),
                    ("pairs", "Pairs"),
                    ("sets", "Sets"),
                    ("boxes", "Boxes"),
                    ("packs", "Packs"),
                    ("dozens", "Dozens"),
                    ("rolls", "Rolls"),
                    ("bundles", "Bundles"),
                    ("cartons", "Cartons"),
                    ("bags", "Bags"),
                    ("sacks", "Sacks"),
                    ("bottles", "Bottles"),
                    ("cans", "Cans"),
                    ("tins", "Tins"),
                    ("containers", "Containers"),
                    ("kg", "Kilograms"),
                    ("g", "Grams"),
                    ("mg", "Milligrams"),
                    ("tonnes", "Tonnes"),
                    ("liters", "Liters"),
                    ("ml", "Milliliters"),
                    ("cl", "Centiliters"),
                    ("gallons", "Gallons"),
                    ("meters", "Meters"),
                    ("cm", "Centimeters"),
                    ("mm", "Millimeters"),
                    ("km", "Kilometers"),
                    ("inches", "Inches"),
                    ("feet", "Feet"),
                    ("yards", "Yards"),
                    ("square_meters", "Square Meters"),
                    ("square_feet", "Square Feet"),
                    ("reams", "Reams"),
                    ("sheets", "Sheets"),
                    ("ream", "Ream"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),

        # ====================================================
        # 4. Add SubDepartment to ReceiptItem
        # ====================================================

        migrations.AddField(
            model_name="receiptitem",
            name="subdepartment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receipt_items",
                to="Receipts.subdepartment",
            ),
        ),

        # ====================================================
        # 5. Convert old department data
        #
        # IMPORTANT:
        # This runs while ReceiptItem.department is STILL
        # the old text field.
        # ====================================================

        migrations.RunPython(
            create_departments_and_migrate_receipt_items,
            migrations.RunPython.noop,
        ),

        # ====================================================
        # 6. NOW convert department to ForeignKey
        # ====================================================

        migrations.AlterField(
            model_name="receiptitem",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receipt_items",
                to="Receipts.department",
            ),
        ),

        # ====================================================
        # 7. ReceiptItem ordering
        # ====================================================

        migrations.AlterModelOptions(
            name="receiptitem",
            options={
                "ordering": ["id"],
            },
        ),

        # ====================================================
        # 8. SubDepartment uniqueness
        # ====================================================

        migrations.AddConstraint(
            model_name="subdepartment",
            constraint=models.UniqueConstraint(
                fields=(
                    "department",
                    "name",
                ),
                name="unique_subdepartment_per_department",
            ),
        ),
    ]