# Generated by Django 5.2.6 on 2025-09-24 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websiteApi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
    ]
