# Generated by Django 5.2.6 on 2025-10-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteApi', '0002_remove_event_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('longDesc', models.TextField()),
                ('image', models.ImageField(upload_to='facilities/')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
