# Generated by Django 5.2.6 on 2025-10-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteApi', '0003_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='shortDesc',
            field=models.TextField(blank=True),
        ),
    ]
