# Generated by Django 5.2.6 on 2025-10-24 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteApi', '0004_facility_shortdesc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('icon_name', models.CharField(help_text='Lucide React icon name (e.g., Baby, BookOpen, Bus, Apple)', max_length=50)),
                ('color_class', models.CharField(default='bg-gray-400', help_text='Tailwind CSS class for background color (e.g., bg-green-400)', max_length=50)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='websiteApi.facility')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
