# Generated by Django 5.2.6 on 2025-10-27 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteApi', '0006_abouthistory_abouthistoryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abouthistoryimage',
            name='about',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='websiteApi.abouthistory'),
        ),
    ]
