# Generated by Django 5.2.6 on 2025-12-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteApi', '0007_alter_abouthistoryimage_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
