# Generated by Django 5.2.6 on 2025-09-29 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransportStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=100)),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
