# Generated by Django 5.2.6 on 2025-09-29 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_transportroute_transportstage'),
        ('students', '0002_alter_student_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransportFee',
        ),
        migrations.AddField(
            model_name='transportstage',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='fees.transportroute'),
        ),
    ]
