# Generated by Django 5.2.6 on 2026-09-24 12:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportstage',
            name='distance_from_previous',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distance from the previous stage in kilometres.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transportstage',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transportstage',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transportstage',
            name='monthly_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current configured monthly transport fee for this stage.', max_digits=10),
        ),
        migrations.AddField(
            model_name='transportstage',
            name='stage_id',
            field=models.CharField(default=52, editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transportstage',
            name='stage_type',
            field=models.CharField(choices=[('pickup', 'Pickup'), ('dropoff', 'Drop-off'), ('both', 'Pickup & Drop-off'), ('school', 'School'), ('stop', 'General Stop')], default='both', max_length=20),
        ),
        migrations.AlterField(
            model_name='transportstage',
            name='landmark',
            field=models.CharField(blank=True, help_text='Nearby landmark or recognizable location.', max_length=255),
        ),
        migrations.AlterField(
            model_name='transportstage',
            name='location_description',
            field=models.TextField(blank=True, help_text='Description of the stage location.'),
        ),
        migrations.AlterField(
            model_name='transportstage',
            name='sequence',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
