# Generated by Django 5.2.6 on 2026-09-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transport', '0002_transportstage_distance_from_previous_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverweeklyreport',
            name='fuel_cost_per_liter',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='driverweeklyreport',
            name='fueling_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='driverweeklyreport',
            name='incidents',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='driverweeklyreport',
            name='maintenance_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='driverweeklyreport',
            name='maintenance_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driverweeklyreport',
            name='vehicle_condition',
            field=models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('critical', 'Critical')], default='good', max_length=20),
        ),
    ]
