# Generated by Django 5.2.6 on 2026-09-23 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(editable=False, help_text='System-generated permanent Staff ID.', max_length=20, unique=True)),
                ('employee_number', models.CharField(help_text='Employee number assigned by the school.', max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20)),
                ('nationality', models.CharField(blank=True, default='Kenyan', max_length=100)),
                ('national_id', models.CharField(blank=True, help_text='National ID or other official identification number.', max_length=100, null=True, unique=True)),
                ('religion', models.CharField(blank=True, choices=[('christianity', 'Christianity'), ('islam', 'Islam'), ('hinduism', 'Hinduism'), ('sikhism', 'Sikhism'), ('buddhism', 'Buddhism'), ('bahai', 'Baháʼí Faith'), ('judaism', 'Judaism'), ('traditional_african_religions', 'African Traditional Religions'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff/photos/')),
                ('phone', models.CharField(max_length=30)),
                ('alternative_phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('subcounty', models.CharField(blank=True, max_length=100)),
                ('date_joined', models.DateField()),
                ('date_left', models.DateField(blank=True, null=True)),
                ('employment_type', models.CharField(choices=[('permanent', 'Permanent'), ('contract', 'Contract'), ('part_time', 'Part-time'), ('casual', 'Casual'), ('intern', 'Intern'), ('volunteer', 'Volunteer')], default='permanent', max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('resigned', 'Resigned'), ('terminated', 'Terminated'), ('retired', 'Retired')], default='active', max_length=30)),
                ('previous_employment', models.TextField(blank=True, help_text='Optional information about previous employment, employers, positions, and experience.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text='Unique internal code for this staff role.', max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StaffReferee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('relationship', models.CharField(blank=True, help_text='Relationship or professional connection to the staff member.', max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('alternative_phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('occupation', models.CharField(blank=True, max_length=150)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referees', to='Staff.staff')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StaffRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_type', models.CharField(choices=[('permanent', 'Permanent'), ('contract', 'Contract'), ('part_time', 'Part-time'), ('casual', 'Casual'), ('intern', 'Intern'), ('volunteer', 'Volunteer')], default='permanent', max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_assignments', to='Staff.staffrole')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='Staff.staff')),
            ],
            options={
                'ordering': ['-start_date', '-id'],
            },
        ),
    ]
